### ISSUE TITLE
allow other node attributes besides 'name' to be used for chef-scout

### ISSUE THREAD

**Issue by michaelkirk** [cgriego/chef-scout#1]
If I want to use the name of my chef node as the name that shows in scout, I can say
node[:scout][:name]="%{name}"

When the recipe runs, we'll then use node[:name]. 

However, we don't use node[:name], we use node[:assigned_hostname], ohai uses node[:hostname]. AFAIK  there's no real convention here - so would you consider merging a change that allows more flexibility here? 

Otherwise I see no way to have the name be externally defined without hacking another recipe to act as intermediary.

**Comment by cgriego** [comment]
I'll gladly accept a change for this if it comes with tests. :smile:
